name: "Contextual QA Checklists"
description: "Submit a comment to PRs with a QA checklist based on context"
inputs:
  gh-token:
    description: "GH Token"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "check-square"
  color: "green"
